### ISSUE TITLE
Why I can't received credit for completing swirl course on Coursera.org?

### ISSUE THREAD

**Issue by andywarta** [swirldev/swirl_courses#252] opened 2016-02-19 02:58 UTC
I'm try to completed R Programming Course (**R Programming Basic Building Blocks** and **R Programming Workspace and Files**) using swirl, but when i try to get credit for completing the course there's error like this:
![image](https://cloud.githubusercontent.com/assets/17173884/13165353/3e801e2a-d6ef-11e5-8623-bf21783ffbe6.png)
Please help
Thanks

**Comment by seankross** [comment] 2016-02-19 18:09
This is a duplicate of swirldev/swirl#413 so I'm closing it.

**Closed by seankross** 2016-02-19 18:09 UTC

**Comment by thakursir** [comment] 2016-03-05 12:12
I am not able to asses assignment of swirl on R-Programming, please help me.
