### ISSUE TITLE
Time to make a more useful function!.....then divide that sum by the number of numbers in the vector.

### ISSUE THREAD

**Issue by money3030** [swirldev/swirl_courses#319] opened 2016-07-12 18:57 UTC
# You're free to implement the function my_mean however you want, as long as it
# returns the average of all of the numbers in `my_vector`.
#
# Hint #1: sum() returns the sum of a vector.
# 	Ex: sum(c(1, 2, 3)) evaluates to 6
#
# Hint #2: length() returns the size of a vector.
# 	Ex: length(c(1, 2, 3)) evaluates to 3
#
# Hint #3: The mean of all the numbers in a vector is equal to the sum of all of
#		   the numbers in the vector divided by the size of the vector.
#
# Note for those of you feeling super clever: Please do not use the mean()
# function while writing this function. We're trying to teach you something 
# here!
#
# Be sure to save this script and type submit() in the console after you make 
# your changes.

my_mean <- function(my_vector) {
  # Write your code here!
  # Remember: the last expression evaluated will be returned! 
  sum(c(4,5,10)) / length(c(4,5,10))
}
I get below error

> submit()

| Sourcing your script...

| You almost had it, but not quite. Try again.

| Use the sum() function to find the sum of all the numbers in the vector. Use the length() function to find the size of the
| vector.

**Comment by seankross** [comment] 2016-07-12 19:02
This issue is a duplicate of https://github.com/swirldev/swirl/issues/508 so I am closing it.

**Closed by seankross** 2016-07-12 19:02 UTC
