### ISSUE TITLE
Problem starting Manipulating Data with dplyr

### ISSUE THREAD

**Issue by kanyhub** [swirldev/swirl_courses#502] opened 2022-05-03 20:48 UTC
HI,
I can't start the course on manipulating data with deplyr.

This is what I get when trying to start it

| Attempting to load lesson dependencies...

| Package ‘dplyr’ loaded correctly!

Error in yaml.load(readLines(con, warn = readLines.warn), error.label = error.label,  : 
  (/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/swirl/Courses/Getting_and_Cleaning_Data/Manipulating_Data_with_dplyr/lesson.yaml) Scanner error: while scanning a tag at line 205, column 9 did not find expected whitespace or line break at line 205, column 19

| Leaving swirl now. Type swirl() to resume.

I have already tried  [this](https://github.com/swirldev/swirl_courses/issues/391#issuecomment-378613319) and [this](https://github.com/swirldev/swirl_courses/issues/498#issuecomment-1094148102).

Anyone with another idea?

**Comment by josevillajulca** [comment] 2022-05-10 19:17
Hi,

From this post: https://github.com/swirldev/swirl_courses/issues/394 , i put a # in the 205 line in the lesson.yaml file and work fine!!!

Hope this help!

**Comment by salhamdani** [comment] 2022-06-01 16:47
@josevillajulca, thank you so much! I'm an R newbie (for now) and this fixed the same issue for me.

**Comment by ViniMig** [comment] 2022-06-11 22:25
Hi guys, I was also facing this issue, and I tried doing something similar to what @josevillajulca did, instead of commenting the whole line 205 (I don't know much of yaml but guessing it will probably make the Hint not appear in the course) I just put the whole text after "Hint" between quotation marks and it solved the issue for me:

Line 205 -> Hint: "!is.na(c(3, 5, NA, 10)) will negate the previous command, thus telling us what is NOT NA."

 Guessing the problem is because of the '!' but just throwing my 2 cents in this! 😄 

Something small anyways, i was trying to find a solution and @josevillajulca 's works.

**Comment by ankeetkumar** [comment] 2022-10-19 04:11
> Hi,
> 
> From this post: #394 , i put a # in the 205 line in the lesson.yaml file and work fine!!!
> 
> Hope this help!

Resolved my issue as well

**Comment by cfsobral** [comment] 2023-02-04 00:16
Hi Guys. So, I'm newbie here. This is my first participation here. 
First, Thank you for tips from ViniMig and anakeetkuma, but I did the following.

I put after Hint: the word "**Try**" and worked fine for me!

**Comment by ncarchedi** [comment] 2023-03-23 12:44
This should be fixed now: https://github.com/swirldev/swirl_courses/pull/517

**Closed by ncarchedi** 2023-03-23 12:44 UTC
